/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uff.ic.labgc.userInterface.gui;

import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Leonardo
 */
public class AboutJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AboutJFrame
     */
    public AboutJFrame() throws IOException {
        initComponents();
        ImageIcon icon = new ImageIcon("Images//Logo.jpg"); 
        AboutImagejLabel.setIcon(icon);
        Font f;
        f = new Font (AboutjTextArea.getFont().getName(),Font.BOLD,AboutjTextArea.getFont().getSize());
        AboutjTextArea.setFont(f);
        
        Image im = null;
        im = Toolkit.getDefaultToolkit().createImage("Images//Logo.jpg");
        this.setIconImage(im);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AboutjPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AboutjTextArea = new javax.swing.JTextArea();
        AboutImagejLabel = new javax.swing.JLabel();
        AboutjButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setTitle("About labgc-2012 -2");
        setAlwaysOnTop(true);

        AboutjTextArea.setColumns(20);
        AboutjTextArea.setEditable(false);
        AboutjTextArea.setRows(5);
        AboutjTextArea.setText("                          Experimental Version Control System \n\n(http://www.ic.uff.br/~leomurta/courses/2012.2/labgc.html)\n\nCoordinator: \tLeoanardo Murta\n\nDevelopers: \tCristiano Cesario\n            \tFelipe Ralph\n            \tFelipe Vieira Duval\n            \tLeonardo Machado\n            \tRaphael Evangelista\n            \tVictor Hugo");
        AboutjTextArea.setToolTipText("             Experimental Version Control System      (http://www.ic.uff.br/~leomurta/courses/2012.2/labgc.html)  Developers:");
        jScrollPane1.setViewportView(AboutjTextArea);

        javax.swing.GroupLayout AboutjPanelLayout = new javax.swing.GroupLayout(AboutjPanel);
        AboutjPanel.setLayout(AboutjPanelLayout);
        AboutjPanelLayout.setHorizontalGroup(
            AboutjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AboutjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AboutjPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AboutImagejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(AboutjPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        AboutjPanelLayout.setVerticalGroup(
            AboutjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AboutjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AboutImagejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        AboutjButton.setText("OK");
        AboutjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutjButtonActionPerformed(evt);
            }
        });
        AboutjButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AboutjButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AboutjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(AboutjButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AboutjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AboutjButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AboutjButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AboutjButtonKeyPressed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_AboutjButtonKeyPressed

    private void AboutjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutjButtonActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
    }//GEN-LAST:event_AboutjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    new AboutJFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(AboutJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AboutImagejLabel;
    private javax.swing.JButton AboutjButton;
    private javax.swing.JPanel AboutjPanel;
    private javax.swing.JTextArea AboutjTextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
