/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uff.ic.labgc.userInterface.gui;

import java.awt.Font;

/**
 *
 * @author Leonardo
 */
public class RepositoryLocationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RepositoryLocationJPanel
     */
    public RepositoryLocationJPanel() {
        initComponents();       
        initTooltips();
    }
    
    private void initTooltips()
    {
        String strRepositoryToolTip = "Fill the repository that you want to perform a checkout";
        RepositoryPaneljLabel.setToolTipText(strRepositoryToolTip);  
    }
    
    public boolean hasRepo()
    {
        if(!RepositoryjTextField.getText().isEmpty())
            return true;
        
        return false;
    }
    
    public String GetRepo()
    {
        return RepositoryjTextField.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RepositoryPaneljLabel = new javax.swing.JLabel();
        RepositoryjTextField = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(466, 216));

        RepositoryPaneljLabel.setText("Repository location");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RepositoryPaneljLabel)
                .addGap(18, 18, 18)
                .addComponent(RepositoryjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RepositoryPaneljLabel)
                    .addComponent(RepositoryjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RepositoryPaneljLabel;
    private javax.swing.JTextField RepositoryjTextField;
    // End of variables declaration//GEN-END:variables
}
