/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uff.ic.labgc.userInterface.gui;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Leonardo
 */
public class WorkspaceLocationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form WorkspaceLocationJPanel
     */
    public WorkspaceLocationJPanel() 
    {
        initComponents();
        AddFileChooser();
        strWorkspace ="";
    }
    
    public String GetWorkspaceLocation()
    {
        //JOptionPane.showMessageDialog(null,fileChooser.getCurrentDirectory().getAbsolutePath());
        return fileChooser.getCurrentDirectory().getAbsolutePath();
    }
    
    private void AddFileChooser()
    {
        fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new java.io.File("."));
        fileChooser.setDialogTitle("choosertitle");
        fileChooser.setFileSelectionMode( JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setAcceptAllFileFilterUsed(false);
        this.setLayout(new BorderLayout());
        this.add(fileChooser, BorderLayout.NORTH);
        fileChooser.addActionListener(new ActionListener() 
        {
         public void actionPerformed(ActionEvent e) 
         {
            if (e.getActionCommand().equals(JFileChooser.APPROVE_SELECTION)) 
            {
               strWorkspace = fileChooser.getSelectedFile().getPath();
            }
         }
      });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setPreferredSize(new java.awt.Dimension(466, 216));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
private String strWorkspace;
private JFileChooser fileChooser;

}
